CREATE DATABASE STUDENT;
USE STUDENT;

CREATE TABLE STUDENT_DETAILS(
STUDENT_ID INT,
STUDENT_NAME VARCHAR (20),
MAIL_ID VARCHAR (100),
MOBILE_NO INT );


CREATE TABLE STUDENT_DETAILS_BACKUP(
STUDENT_ID INT,
STUDENT_NAME VARCHAR (20),
MAIL_ID VARCHAR (100),
MOBILE_NO INT );


INSERT INTO 
STUDENT_DETAILS
VALUES
(1,'RAM','RAM123@GMAIL.COM',987456321),
(2,'LAXMAN','LAXMAN234@GMAIL.COM',879654330),
(3,'BHARAT','BHARAT342@GMAIL.COM',789654130);


DELIMITER //

CREATE TRIGGER STUDENT_DETAILS_BACKUP
BEFORE DELETE ON STUDENT_DETAILS
FOR EACH ROW
BEGIN
    INSERT INTO STUDENT_DETAILS_BACKUP (STUDENT_ID,STUDENT_NAME,MAIL_ID,MOBILE_NUMBER)
    VALUES (OLD.STUDENT_ID, OLD.STUDENT_NAME, OLD.MAIL_ID, OLD.MOBILE_NUMBER);
END;
//

DELIMITER ;

SET SQL_SAFE_UPDATES=0;


DELETE FROM Student_details WHERE STUDENT_ID = 1;

COMMIT;